name: 'Generate Calver Version'
description: 'Calculate Calver version and set VERSION environment variables.'
inputs:
  prefix:
    default: ''
    required: false
    description: 'Version prefix'
  suffix:
    default: ''
    required: false
    description: 'Version suffix'
  format:
    default: 'YYYYMMDD'
    required: true
    description: 'Day.js compatible date format string'
  subversion: 
    default: 'build'
    required: false
    description: 'Type of subversioning. You can chose between build'
outputs:
  version:
    description: 'The version number'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: bookmark
  color: red