name: Test the action
on: 
  push: 
    branches: ['main']

jobs: 
  build:
    runs-on: ubuntu-latest
    name: 'Local test'
    steps: 
      - name: Fetch Repo Code 
        uses: actions/checkout@
        
      - name: Build
        run: |
          npm i
          npx tsc

      - name: Set Version 
        uses: ./ 
        id: calvergenerator
        with: 
          format: 'YYYYMMDD'
          prefix: 'v'
        