name: Test the action
on: 
  push: 
    branches: ['main']

jobs: 
  build:
    runs-on: ubuntu-latest
    name: 'Local test'
    steps: 
      - name: Fetch Repo Code 
        uses: actions/checkout@v4
        
      - name: Build
        run: |
          npm i
          npm run build

      - name: Set Version 
        uses: ./ 
        id: calvergenerator
        with: 
          format: 'YYYYMMDD'
          prefix: 'v'

      - name: Get version
        run: |
          echo "The version was ${{ steps.calvergenerator.outputs.version }}"
        